<a href="https://colab.research.google.com/github/khairulsholech/google-collab/blob/main/PM7_DML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pengenalan NumPy Arrays**

**Membuat Array**

In [ ]:
import numpy as np

In [ ]:
# Membuat array
a = np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
b = np.array([1,2,3.0])
b

array([1., 2., 3.])

**Cek Tipe**

In [ ]:
# Mengecek tipe data array
type(a)

numpy.ndarray

**Tipe Data untuk Element**

In [ ]:
a = np.array([1,2,3])
a.dtype

dtype('int64')

**Jumlah Dimensi**

In [ ]:
# Cek jumlag dimensi pada array
a = np.array([1,2,3])
a.shape

(3,)

**Operasi pada Array**

In [ ]:
a = np.array([1,2,3])
f = np.array([1.1, 2.2, 3.3])
a + f

array([2.1, 4.2, 6.3])

In [ ]:
a * f

array([1.1, 4.4, 9.9])

In [ ]:
a ** f

array([ 1.        ,  4.59479342, 37.5405076 ])

In [ ]:
# Universal function (ufuncs) pada numpy seperti sin
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

**Element pada Array**

**Array Indexing**

In [ ]:
# Mengakses elemen pada indeks ke-0
a = np.array([1,2,3])
a[0]

1

In [ ]:
# Melakukan assign pada element array dengan element baru
a[0] = 10
a

array([10,  2,  3])

In [ ]:
a = np.array([1,2,3])
a.dtype

dtype('int64')

In [ ]:
# Assign nilai baru pada indeks ke-0
a[0] = 11.6
a

array([11,  2,  3])

**Multi-Dimensional Arrays**

In [ ]:
# Membentuk array 2-dimensi
a = np.array([[0, 1, 2, 3],[10,11,12,13]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [ ]:
a.shape

(2, 4)

In [ ]:
a.size

8

In [ ]:
a.ndim

2

In [ ]:
a[1,3]

13

In [ ]:
a[1, 3] = -1
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, -1]])

**Slicing**

In [ ]:
a = np.array([1,2,3])
# slicing dari indeks ke-1, dan batas indeks ke-2
a[1:2]

array([2])

In [ ]:
# slicing dari indeks ke-1, dan batas indeks ke-1 dari belakang
a[1:-1]

array([2])

In [ ]:
a[::2]

array([1, 3])

**LATIHAN**

**Kelompok 3**
- Aliffio Syah Maulana - 41519120065
- Khairul Sholech - 41519120068
- Reza Arrofi - 41519120044

**Operasi Aritmatika**

Kita bisa menggunakan operasi aritmatika seperti penjumlahan, pengurangan, perkalian,
pembagian dan perpangkatan
Operator yang digunakan adalah +, -, *, / dan **


Berikut contoh oparr_A = np.array([1,2,3,4,5])

In [ ]:
arr_A = np.array([1,2,3,4,5])
arr_B = np.array([2,2,2,2,2])

print("Penjumlahan = ", arr_A + arr_B)
print("Pengurangan = ", arr_A - arr_B)
print("Perkalian = ", arr_A * arr_B)
print("Pembagian = ", arr_A / arr_B)
print("Perpangkatan = ", arr_A ** arr_B) #operasi aritmatika pada array

Penjumlahan =  [3 4 5 6 7]
Pengurangan =  [-1  0  1  2  3]
Perkalian =  [ 2  4  6  8 10]
Pembagian =  [0.5 1.  1.5 2.  2.5]
Perpangkatan =  [ 1  4  9 16 25]


**Operasi Matematika**

NumPy mempunyai fungsi matematika yang dapat digunakan pada Array
Beberapa contoh fungsi statistik antara lain min(), max(), mean(), sum(), std()

In [ ]:
arrku = np.array([1,2,3,4,5])
print("Nilai minimal = ", arrku.min())
print("Nilai maksimal = ", arrku.max())
print("Nilai rata-rata = ", arrku.mean())
print("Total nilai = ", arrku.sum())
print("Standar Deviasi = ", arrku.std())

#Ada juga fungsi argmin() dan argmax() untuk mendapatkan index dari nilai minimum dan maksimum
print("Index nilai niminal = ", arrku.argmin())
print("Index nilai maksimal = ", arrku.argmax())

Nilai minimal =  1
Nilai maksimal =  5
Nilai rata-rata =  3.0
Total nilai =  15
Standar Deviasi =  1.4142135623730951
Index nilai niminal =  0
Index nilai maksimal =  4


Ada beberapa fungsi lagi yang dapat digunakan dalam membuat array antara lain zeros(), ones(), arange(), linspace(), logspace(),


*   zeros() -> Membuat array dengan nilai 0
*   ones() -> Membuat array dengan nilai 1
*   arange() -> Membuat array dengan nilai dalam range
*   linspace() -> Membuat array dengan nilai dalam interval
*   logspace() -> Membuat array dengan nilai log Base10 dalam interval

In [ ]:
np.zeros(5) # membuat array dengan nilai 0 sebanyak 5

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(5) # membuat array dengan nilai 1 sebanyak 5

array([1., 1., 1., 1., 1.])

In [ ]:
np.arange(1, 10, 2) #arange(start, stop, step)

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(1, 10, 2) # linespace(start, stop, number)

array([ 1., 10.])

In [ ]:
np.logspace(1, 10, 2) # logspace(start, stop, number)

array([1.e+01, 1.e+10])